color:
  brandColors:
    - '#D7DCD6'
    - '#787799'
    - '#C9BA29'
    - '#124D2F'
    - '#B23438'
  brandStrength: 0.646115
  lightness: 0.800455
  rhythmicContrast: 0.788992
  saturation: 0.699311
layout_spectrum: 0.239865
name: Paradigma
typography_spectrum: 0.146115
